server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # 핵심: 못 찾는 주소는 무조건 index.html로 돌려보냄
        try_files $uri $uri/ /index.html;
    }
}
